name: Execute Test
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jensg-st/direktiv-actions@test
      - name: Get the output time
        run: echo "done"
