name: Execute Test
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test workflow execution
    steps:
      - name: execute
        id: execute
        with:
          wait: false
          server: playground.direktiv.io
          workflow: jens/action
          token: ${{ secrets.DIREKTIV_TOKEN }}
          data: |
            {
              "data": "one"
            }
        uses: jensg-st/direktiv-actions@test
      - name: get the output
        run: |
          echo "context id: $WF_VALUE"
        env:
          WF_VALUE: ${{join(steps.execute.outputs.*, '\n')}}
