name: Execute Test
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test workflow execution
    steps:
      - name: execute
        with:
          server: playground.direktiv.io
          workflow: jens/myreq
          token: ${{ secrets.DIREKTIV_TOKEN }}
          data: |
            {
              "data": "one"
            }
        uses: jensg-st/direktiv-actions@test
      - name: Get the output time
        run: echo "done"
